poll_interval: 1
test_configuration:
  report: lighthouse
  simulate_device: nexus_5
  url: https://www.google.com
  video: true
requirements:
  structure_score: 94
  onload_duration: 40
  gtmetrix_grade: A